### ISSUE TITLE
Fuse not working under OS X

### ISSUE THREAD

**Issue by evianzhow** [maxint/kuaipan#2]
It may related to a problem of fuse on OS X. Fuse on OS X doesn't have a option named `nonempty`.

fuse: unknown option `nonempty'
[E] kpfuse - kpfuse command failed
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/site-packages/kpfuse/command.py", line 111, in main
    launch(**vars(args))
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/site-packages/kpfuse/command.py", line 82, in launch
    ro=False)  # readonly
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/site-packages/fuse.py", line 399, in **init**
    raise RuntimeError(err)
RuntimeError: 1
mount_osxfusefs: failed to mount /Users/Yifei/KuaiBox@/dev/osxfuse0: Socket is not connected

pyenv + python 2.7.8 + OS X Yosemite

**Comment by maxint** [comment]
Hi Austin,

Thanks for reporting this issue with so much detail! I have disable the "nonempty" option.  You could have a try.

B. R.
maxint

**Comment by evianzhow** [comment]
Thanks for the quick response. I've tried reinstall(upgrade) kpfuse on my system, and there is another problem and I pasted the traceback below. I'm not sure whether this problem is cause by pyenv on my system or something else. Please have a look.

Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/2.7.8/bin/kpfs", line 9, in <module>
    load_entry_point('kpfuse==0.4.1', 'console_scripts', 'kpfs')()
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/site-packages/pkg_resources/**init**.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2345, in load
    return self.resolve()
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2351, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
ImportError: No module named command

**Comment by maxint** [comment]
Hi Austin,

It's a bug after I rename the module name :cry: . Please check the latest version for bug fix. May be more unit tests is needed to make the script more robust.

Thanks again for your report!

B. R.
maxint

**Comment by evianzhow** [comment]
Yes. Latest version works.

But under OS X, FUSE doesn't operate so well. If you are using OS X, please have a try. Sometimes I can't sync with the remote, get stuck when creating files. I doubt that these behaviors are related to OSXFuse itself.

**Comment by maxint** [comment]
It may be a bug, I just fix some bugs related with file creating and uploading (v0.5.2). More tests are needed seriously before making it work well for all cases. According to tests by myself, read-only operations has better experiences.
